name: Build Spring Application with Maven

on:
  workflow_run:
    workflows: ["Trigger Salary CI Workflow"]  # Listen to the root-level workflow trigger
    types:
      - completed  # Trigger only when the root-level workflow completes

Jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build project with Maven
      run: |
        mvn clean package -DskipTests
        ls target
