name: Trigger Salary CI Workflow

on:
  push:
    branches:
      - master
    paths:
      - 'salary/**'  # Trigger only when files in the salary folder change

jobs:
  trigger:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/java-ci.yml

    # steps:
    #   # Step 1: Checkout the repository
    #   - name: Checkout Code
    #     uses: actions/checkout@v3

    #   - name: List workdir
    #     run: |
    #       ls
    #       pwd
      
      
        # run: |
        #   # Define variables
        #   WORKFLOW="java-ci"
        #   API_URL="https://api.github.com/repos/${{ github.repository }}/actions/workflows/"$WORKFLOW".yml/dispatches"
        #   TOKEN="${{ secrets.GITHUB_TOKEN }}"
          
        #   # Trigger the second workflow
        #   curl -X POST "$API_URL" \
        #     -H "Accept: application/vnd.github.v3+json" \
        #     -H "Authorization: Bearer $TOKEN" \
        #     -d '{"ref": "main"}'